import { useEffect, useState } from "react";
import { ArrowLeft, Minus, Plus, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
export default function CartPage({ cart, onUpdateQuantity, onRemove }) {
  const [promoCode, setPromoCode] = useState(""); const [promoMessage, setPromoMessage] = useState("");
  const subtotal = cart.reduce((total, item) => total + item.price * item.quantity, 0); const shipping = subtotal === 0 || subtotal >= 150 ? 0 : 15;
  useEffect(() => { document.title = "Your Cart | GymGrid"; }, []);
  const applyPromo = (event) => { event.preventDefault(); setPromoMessage(promoCode.trim().toUpperCase() === "FORGE10" ? "FORGE10 accepted — 10% will be applied at checkout." : "Enter FORGE10 to try a demo offer."); };
  if (!cart.length) return <div className="cart-page empty-cart"><p className="eyebrow">Your cart</p><h1>Ready when you are.</h1><p>Your cart is empty. Start building a setup you’ll look forward to using.</p><Link className="primary-link" to="/">Browse equipment <ArrowLeft size={17} /></Link></div>;
  return <div className="cart-page"><Link className="back-link" to="/"><ArrowLeft size={17} /> Continue shopping</Link><p className="eyebrow">Your cart</p><h1>Built to move with you.</h1><div className="cart-layout"><section className="cart-items" aria-label="Cart items">{cart.map((item) => <article className="cart-item" key={item.id}><img src={item.image} alt="" /><div className="cart-item-details"><p>{item.category}</p><h2>{item.name}</h2><strong>${item.price}</strong></div><div className="cart-actions"><div className="quantity-control"><button type="button" aria-label={`Remove one ${item.name}`} onClick={() => onUpdateQuantity(item.id, item.quantity - 1)}><Minus size={15} /></button><span>{item.quantity}</span><button type="button" aria-label={`Add one ${item.name}`} onClick={() => onUpdateQuantity(item.id, item.quantity + 1)}><Plus size={15} /></button></div><button type="button" className="remove-button" onClick={() => onRemove(item.id)}><Trash2 size={16} /> Remove</button></div></article>)}</section><aside className="summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>${subtotal.toFixed(2)}</strong></div><div><span>Shipping</span><strong>{shipping ? `$${shipping.toFixed(2)}` : "Free"}</strong></div><div className="total"><span>Total</span><strong>${(subtotal + shipping).toFixed(2)}</strong></div><form onSubmit={applyPromo}><label htmlFor="promo">Promo code</label><div><input id="promo" value={promoCode} onChange={(event) => setPromoCode(event.target.value)} placeholder="Try FORGE10" /><button>Apply</button></div>{promoMessage && <p className="promo-message">{promoMessage}</p>}</form><button className="checkout-button" type="button">Secure checkout</button><p className="shipping-note">Free shipping on orders over $150.</p></aside></div></div>;
}
