import { useEffect, useMemo, useState } from "react";
import { Dumbbell, Search, SlidersHorizontal, Trophy, Zap } from "lucide-react";
import ProductCard from "./ProductCard";
import ProductModal from "./ProductModal";
import { categories, equipment } from "../data/equipment";
export default function CatalogPage({ onAddToCart, wishlist, onToggleWishlist }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [sortBy, setSortBy] = useState("featured");
  const [selectedProduct, setSelectedProduct] = useState(null);
  useEffect(() => { document.title = "GymGrid | Gym Equipment"; }, []);
  const visibleEquipment = useMemo(() => [...equipment.filter((item) => (category === "All" || item.category === category) && item.name.toLowerCase().includes(query.trim().toLowerCase()))].sort((a, b) => sortBy === "price-low" ? a.price - b.price : sortBy === "price-high" ? b.price - a.price : sortBy === "rating" ? b.rating - a.rating : a.id - b.id), [category, query, sortBy]);
  return <div className="page-shell"><section className="hero-section"><p className="eyebrow">Built for the work</p><h1>Train hard.<br /><em>Anywhere.</em></h1><p>Premium equipment for a gym that fits your goals, your space, and your schedule.</p><div className="hero-points"><span>✓ Trusted gear</span><span>✓ Built to last</span><span>✓ Expert support</span></div><div className="training-strip" aria-label="GymGrid training benefits"><div><Dumbbell size={21} /><span><strong>Strength first</strong>Build a gym that grows with you</span></div><div><Zap size={21} /><span><strong>Made to move</strong>Performance gear for every session</span></div><div><Trophy size={21} /><span><strong>Progress daily</strong>Train for your next personal best</span></div></div></section><section className="catalog-section" aria-labelledby="catalog-title"><div className="catalog-heading"><div><p className="eyebrow">Shop equipment</p><h2 id="catalog-title">Find your next personal best</h2></div><p className="result-count">{visibleEquipment.length} products</p></div><div className="filters" aria-label="Catalog filters"><label className="search-box"><Search size={18} /><span className="sr-only">Search equipment</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search equipment" /></label><label className="select-box"><SlidersHorizontal size={17} /><span className="sr-only">Sort products</span><select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="rating">Top rated</option></select></label></div><div className="category-list">{categories.map((item) => <button type="button" key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div>{visibleEquipment.length ? <div className="product-grid">{visibleEquipment.map((item) => <ProductCard key={item.id} item={item} onAddToCart={onAddToCart} isSaved={wishlist.includes(item.id)} onToggleWishlist={onToggleWishlist} onQuickView={setSelectedProduct} />)}</div> : <div className="empty-state"><h3>No equipment found</h3><p>Try a different search or browse every category.</p><button type="button" onClick={() => { setQuery(""); setCategory("All"); }}>Clear filters</button></div>}</section>{selectedProduct && <ProductModal item={selectedProduct} onClose={() => setSelectedProduct(null)} onAddToCart={onAddToCart} />}</div>;
}
